/* This file was auto-generated by Mandarin compiler */
#include <csetjmp>
#include <cstddef>
#include <cstdint>
#include <memory>
namespace mandarin {namespace user {
}} /* namespace mandarin::user */
int main(int argc, char** argv)
{
    mandarin::support::preinit()
    mandarin::support::store_args(argc, argv);
    auto scoped_init = mandarin::support::init();
    mandarin::user::main();
    return 0;
}
